name: sample docfx-build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Set up zlib-static
      run: sudo apt-get install -y libkrb5-dev
    - name: Build
      # Doing a full build here for simplicity. This can be limited to the core projects.
      # However, as noted in the PR, building them before building the docs is neccessary.
      run: ./build.sh --target Build
    - name: Build docs
      run: dotnet run --project ./build/Build.csproj --no-build -- --target DocFx_Build
    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        #force_orphan: true    
